### ISSUE TITLE
realesrgan doesn't appear to be functioning

### ISSUE THREAD

**Issue by caacoe** [sczhou/CodeFormer#14]
Hi, this tool is absolutely amazing, not using it for it's intended purpose per se, but it produces incredible results regardless.

I'm interested in the new option for BG upscaling via realesrgan, however when I use the flag --bg_upsampler realesrgan, results are identical in comparison without this flag, processing time is suspicously similar too.

RealESRGAN_x2plus.pth is located in the approprate folder too `./weights/realesrgan/RealESRGAN_x2plus.pth`

Is it possible that I'm missing something?

**Comment by sczhou** [comment]
> I'm interested in the new option for BG upscaling via realesrgan, however when I use the flag --bg_upsampler realesrgan, results are identical in comparison without this flag, processing time is suspicously similar too.
> 
> RealESRGAN_x2plus.pth is located in the approprate folder too `./weights/realesrgan/RealESRGAN_x2plus.pth`
> 
> Is it possible that I'm missing something?

Hi, thank you for acknowledging our work!

Did you check if the GPU is available? Since RealESRGAN is slow on CPU, we do not use it on CPU by default.
You can have a simple debug at here: https://github.com/sczhou/CodeFormer/blob/master/inference_codeformer.py#L38

If you want to perform RealESRGAN on CPU, you can just comment out the `if not torch.cuda.is_available()` statement.

**Comment by FlowDownTheRiver** [comment]
@sczhou Thank you very much for the background upscale update.

**Comment by caacoe** [comment]
Thank you for all of this work generally, this is absolutely brilliant!
